# 1. Download a small sample of IPL match data (CSV) with some missing values in player stats. Load it using pandas and print the number of missing values in each column.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('matches.csv')
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [5]:
df.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

# 2. For the 'player_age' column in your IPL dataset, fill all missing values with the median age using pandas' fillna() method and display the updated column.

In [7]:
median_margin = df['result_margin'].median()

In [8]:
df['median_margin'] = df['result_margin'].fillna(median_margin)

In [11]:
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,median_margin
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,140.0
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,33.0
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,9.0
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,5.0
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,5.0

In [14]:
df.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
median_margin         0
dtype: int64

# 3. Suppose the 'team' column in your IPL dataset contains missing values. Replace all missing team names with the constant value 'Unknown' and print the first 10 rows.

In [15]:
df['city'] = df['city'].fillna('Unknown')

In [20]:
df.isnull().sum()

id                    0
season                0
city                  0
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
median_margin         0
dtype: int64

In [19]:
df.head(10)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,median_margin
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,140.0
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,33.0
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,9.0
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,5.0
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,5.0
5,335987,2007/08,Jaipur,2008-04-21,League,SR Watson,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,...,Rajasthan Royals,wickets,6.0,167.0,20.0,N,NaN,Aleem Dar,RB Tiffin,6.0
6,335988,2007/08,Hyderabad,2008-04-22,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,...,Delhi Daredevils,wickets,9.0,143.0,20.0,N,NaN,IL Howell,AM Saheba,9.0
7,335989,2007/08,Chennai,2008-04-23,League,ML Hayden,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Mumbai Indians,Mumbai Indians,...,Chennai Super Kings,runs,6.0,209.0,20.0,N,NaN,DJ Harper,GA Pratapkumar,6.0
8,335990,2007/08,Hyderabad,2008-04-24,League,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,Rajasthan Royals,...,Rajasthan Royals,wickets,3.0,215.0,20.0,N,NaN,Asad Rauf,MR Benson,3.0
9,335991,2007/08,Chandigarh,2008-04-25,League,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,...,Kings XI Punjab,runs,66.0,183.0,20.0,N,NaN,Aleem Dar,AM Saheba,66.0

# 4. Take the 'venue' column (categorical) from your IPL dataset and apply one-hot encoding using pandas' get_dummies(). Show the resulting DataFrame with the new columns.

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1095 non-null   str
 3   date             1095 non-null   str
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
 20  median_margin    1095 non-null   float64
dtypes: float64(4), int64(1), str(16)
memory usage: 361.1 KB

In [26]:
df['venue'].unique()

<ArrowStringArray>
[                                                'M Chinnaswamy Stadium',
                            'Punjab Cricket Association Stadium, Mohali',
                                                      'Feroz Shah Kotla',
                                                      'Wankhede Stadium',
                                                          'Eden Gardens',
                                                'Sawai Mansingh Stadium',
                             'Rajiv Gandhi International Stadium, Uppal',
                                       'MA Chidambaram Stadium, Chepauk',
                                            'Dr DY Patil Sports Academy',
                                                              'Newlands',
                                                      'St George's Park',
                                                             'Kingsmead',
                                                       'SuperSport Park',
                                                          'Buffalo Park',
                                                 'New Wanderers Stadium',
                                                 'De Beers Diamond Oval',
                                                       'OUTsurance Oval',
                                                     'Brabourne Stadium',
                                          'Sardar Patel Stadium, Motera',
                                                      'Barabati Stadium',
                                             'Brabourne Stadium, Mumbai',
                          'Vidarbha Cricket Association Stadium, Jamtha',
                          'Himachal Pradesh Cricket Association Stadium',
                                                         'Nehru Stadium',
                                                'Holkar Cricket Stadium',
                   'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
                                            'Subrata Roy Sahara Stadium',
                               'Maharashtra Cricket Association Stadium',
                      'Shaheed Veer Narayan Singh International Stadium',
                                    'JSCA International Stadium Complex',
                                                  'Sheikh Zayed Stadium',
                                               'Sharjah Cricket Stadium',
                                   'Dubai International Cricket Stadium',
                  'Punjab Cricket Association IS Bindra Stadium, Mohali',
                                'Saurashtra Cricket Association Stadium',
                                                            'Green Park',
                                                 'M.Chinnaswamy Stadium',
                          'Punjab Cricket Association IS Bindra Stadium',
                                    'Rajiv Gandhi International Stadium',
                                                'MA Chidambaram Stadium',
                                                  'Arun Jaitley Stadium',
                              'MA Chidambaram Stadium, Chepauk, Chennai',
                                              'Wankhede Stadium, Mumbai',
                                      'Narendra Modi Stadium, Ahmedabad',
                                           'Arun Jaitley Stadium, Delhi',
                                      'Zayed Cricket Stadium, Abu Dhabi',
                                    'Dr DY Patil Sports Academy, Mumbai',
                         'Maharashtra Cricket Association Stadium, Pune',
                                                 'Eden Gardens, Kolkata',
      'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
                  'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
                                      'M Chinnaswamy Stadium, Bengaluru',
                                   'Barsapara Cricket Stadium, Guwahati',
                                        'Sawai Mansingh Stadium, Jaipur',
              'Himachal Pradesh Cricket Association Stadium, Dharamsala',
    'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
    'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam']
Length: 58, dtype: str

In [27]:
venue_encoded = pd.get_dummies(df, columns=['venue'], dtype=int)

In [31]:
venue_encoded.head()

,id,season,city,date,match_type,player_of_match,team1,team2,toss_winner,toss_decision,...,venue_Shaheed Veer Narayan Singh International Stadium,venue_Sharjah Cricket Stadium,venue_Sheikh Zayed Stadium,venue_St George's Park,venue_Subrata Roy Sahara Stadium,venue_SuperSport Park,"venue_Vidarbha Cricket Association Stadium, Jamtha",venue_Wankhede Stadium,"venue_Wankhede Stadium, Mumbai","venue_Zayed Cricket Stadium, Abu Dhabi"
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,...,0,0,0,0,0,0,0,0,0,0
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,...,0,0,0,0,0,0,0,0,0,0
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,...,0,0,0,0,0,0,0,0,0,0
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,...,0,0,0,0,0,0,0,1,0,0
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,...,0,0,0,0,0,0,0,0,0,0

# 5. Use LabelEncoder from sklearn to encode the 'player_role' column (e.g., Batsman, Bowler, Allrounder) in your IPL dataset, and display the mapping from original roles to encoded values.<br><br><em><strong>Hint:</strong> Use LabelEncoder's classes_ attribute to see the mapping.

In [32]:
df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2', 'median_margin'],
      dtype='str')

In [33]:
from sklearn.preprocessing import LabelEncoder

In [34]:
le = LabelEncoder()

In [35]:
df['toss_label_encoded'] = le.fit_transform(df['toss_decision'])

In [37]:
print("--- Label Encoding Mapping ---")
for index, class_label in enumerate(le.classes_):
    print(f"Original Value: '{class_label}' ===> Encoded Integer: {index}")

--- Label Encoding Mapping ---
Original Value: 'bat' ===> Encoded Integer: 0
Original Value: 'field' ===> Encoded Integer: 1

In [36]:
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,median_margin,toss_label_encoded
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,140.0,1
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,33.0,0
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,9.0,0
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,5.0,0
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,5.0,0